In [29]:
import numpy as np
A=np.array([[22,5,16,9], [13,20,19,0],[5,9,1,16],[27,13,15,19]])
B=np.array([[10,5,20,20], [5,21,22,27],[26,19,22,3],[27,8,18,7]])
c=np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
d=np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

print('1',A+B)
print('2',A-B)
print('3',A*B)
print('4', np.matmul(A,B))
print('5', c+d)
print('6', c-d)
print('7', c*d)
print('8', np.dot(c,d))
print('9', A+10)
print('10', B+10)
print('11', c+15)
print('12', d+15)
# print('orig13', A.T+B)
# print('orig14', B.T-A)
# print('orig15', np.linalg.det(A))
# print('16', np.linalg.det(B))
print('13', (2*A) + (2*B))
print('14', (A + B) * 3)
print('15', (A-B+A-B+B)*4)

1 [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
2 [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
3 [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]
4 [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
5 [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
6 [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
7 [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
8 2298
9 [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
10 [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]
11 [39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
12 [18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
orig13 [[32 18 25 47]
 [10 41 31 40]
 [42 38 23 18]
 [36  8 34 26]]
orig14 [[-12   0  10  18]
 [ -8   1   0   8]
 [ 15  13  21   2]
 [ -7  14 -12 -12]]
orig15 25523.999999999996
16 -64080.0
13 [[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108 