In [0]:
import tensorflow as tf

In [0]:
x = tf.placeholder(dtype=tf.float32)

In [0]:
y = tf.pow((2 * x), 2) + (2*x) + 1

In [0]:
init_op = tf.global_variables_initializer()

In [0]:
sess = tf.Session()

In [0]:
sess.run(init_op)

In [0]:
value = sess.run(y, feed_dict={x: 10})

In [9]:
print(value)

421.0


In [0]:
weights = tf.Variable(tf.random_normal(shape=[10]))


In [11]:
sess.run(tf.global_variables_initializer())
sess.run(weights)

array([ 0.41097182,  0.24907863,  1.0661308 ,  0.56643736, -1.1552471 ,
       -1.3236833 , -0.1640344 , -0.33864897, -2.1524553 , -0.6724794 ],
      dtype=float32)

In [0]:
from sklearn.datasets import load_iris
import numpy as np

In [0]:
x = load_iris().data
y = load_iris().target

In [14]:
x[:10], y[:10], x.shape

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (150, 4))

In [0]:
input_features = tf.placeholder(dtype=tf.float32,
                                shape = [None, x.shape[1]])
input_labels = tf.placeholder(dtype=tf.float32,
                             shape = [None, 3])

weights = tf.Variable(tf.random_normal(shape=[x.shape[1], 3]))
biases = tf.Variable(tf.random_normal(shape=[3]))
linear_model = tf.add(tf.matmul(input_features,weights), biases)

loss = tf.reduce_mean(tf.square(linear_model - input_labels))
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [0]:
def next_batch(batch_size, features, labels):
  indices = np.arange(start=0, stop=features.shape[0])
  np.random.shuffle(indices)
  indices = indices[:batch_size]
  return features[indices], labels[indices]

In [18]:
batch_size = 16
for epoch in range(10):
  for index in range(int(x.shape[0] / batch_size)):
    mini_batch_x, mini_batch_y = next_batch(batch_size = batch_size, features =x, labels=y)
    
    
    from keras.utils import to_categorical
    mini_batch_y = to_categorical(mini_batch_y)
    _, train_loss = sess.run([train_op, loss], feed_dict={
        input_features: mini_batch_x,    
        input_labels: mini_batch_y
    })

  print('Epoch {}, loss: {}'.format(epoch, train_loss))

Using TensorFlow backend.


Epoch 0, loss: 14.571497917175293
Epoch 1, loss: 8.681635856628418
Epoch 2, loss: 3.825040817260742
Epoch 3, loss: 1.5636926889419556
Epoch 4, loss: 0.9749948382377625
Epoch 5, loss: 0.8883118629455566
Epoch 6, loss: 0.5033895969390869
Epoch 7, loss: 0.30517086386680603
Epoch 8, loss: 0.2949698865413666
Epoch 9, loss: 0.22195537388324738


In [38]:
indices = np.arange(start=0, stop=x.shape[0])
indices


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [39]:
np.random.shuffle(indices)
indices

array([138,  73, 135,  51, 124,  99,  19,  59, 146,  21,  70,  46,  58,
        68,  63,   7, 136,  85,  22,  95,  12,  88,  71, 110,  31, 145,
         6,  80,  37,  35, 121, 102,  76, 125,  44, 116, 109, 101,  50,
       120,  32,  25,  27,  86, 111, 113,  81, 103,   5,  39,  11,  47,
       129,  57,  23,  77, 114,  90,  41, 144, 131,  64, 123, 118,  14,
        98, 107,  84,  94,  97, 147,  53, 142, 106, 117,  79, 126,  78,
       132, 119, 134,  40,  65,  29,  43,  18,  24,  36,  91, 112, 115,
        48,  62,   8, 104,   0,  33,  55,  82, 148, 149,  75,  13, 130,
        74, 139,  67,  49,  54,  56,  87,  10, 133,  15, 143,  38,  92,
         2,  42,  45,  93,  69,  28,   4, 140,  30,  34, 141, 122,  96,
       128, 127,  83, 108,  89,  17,  52,   1,   9,  72, 137, 105, 100,
        20,  60,   3,  61,  66,  16,  26])